services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: os-backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./back-end/.env
    ports:
      - "4000:4000"

  postgres:
    image: postgres:15
    container_name: os-postgres
    restart: always
    environment:
      POSTGRES_DB: osdev
      POSTGRES_USER: osuser
      POSTGRES_PASSWORD: ospassword
    ports:
      - "5432:5432"
    volumes:
      - osdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U osuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  osdb_data:
